### ISSUE TITLE
radar visualization

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-plot#108]
This will be a recreation of the d3plus 1.0 [radar](http://d3plus.org/examples/basic/5c57d9d71aa309d180c2/) visualization.

Here is the old logic (sorry for the coffeescript 😬): https://github.com/alexandersimoes/d3plus/blob/master/src/viz/types/radar.coffee

**Comment by cnavarreteliz** [comment]
For the future's @cnavarreteliz:

Check position of the box

![image](https://user-images.githubusercontent.com/5233593/44490110-c98ffd80-a633-11e8-9d03-a9c58ed96c87.png)
