### ISSUE TITLE
in dense bar chart, bars disappear as container shrinks with default settings

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-plot#45]
### Expected Behavior

Expected behavior is that bars will always be visible when shrinking.

### Current Behavior

All bars disappear when the window reaches a certain smaller size.

### Steps to Reproduce (for bugs)

See https://jsfiddle.net/qnL6tn08/

### Your Environment

* Browser Name: Chrome/Firefox
* Operating System and Version: OS X

**Comment by davelandry** [comment]
That's an issue with the `barPadding` and `groupPadding` methods. The values are currently `5` and `20` respectively, which is... kind of big for small bar charts with a lot of bars. I think I've found some better defaults: https://jsfiddle.net/qnL6tn08/19/

In the meantime, you can just set those manually until I release the next version of d3plus-plot.
