### ISSUE TITLE
strokeWidth not applied to LinePlot?

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-plot#46]
### Expected Behavior

User can vary the stroke width of a plotted line
### Current Behavior

Setting  the strokeWidth doesn't seem to change the width of the line

```js
{
  shapeConfig: {Path: {
    stroke: "rgba(7, 94, 128, 0.5)",
    strokeWidth: "4px"
  }
}

```

### Steps to Reproduce (for bugs)
See https://jsfiddle.net/hxwn785q/1/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: OS X

**Comment by davelandry** [comment]
You need to be modifying the "Line" shape:

```js
shapeConfig: {Line: {
    stroke: "rgba(7, 94, 128, 0.5)",
    strokeWidth: "5px"
  }}
```

https://jsfiddle.net/hxwn785q/2/

**Comment by davelandry** [comment]
http://d3plus.org/examples/d3plus-plot/line-plot-strokeWidth/
