### ISSUE TITLE
After d3plus update d3plus-plot stop working

### ISSUE THREAD

**Issue by palamago** [d3plus/d3plus-plot#53]
After the last update of datawheel-canon  v.0.10.0  that use lastest version of d3plus, some plot charts stop working.
Are there changes on config settings?

### Steps to Reproduce (for bugs)

1. The config:
```javascript
<LinePlot
            config={{
              height: 500,
              data: path,
              groupBy: "variable",
              x: "ID Year",
              y: "value"
            }}
            dataFormat={data =>
              melt(data.data, ["ID Year"], ["FOB", "CIF", "Trade Balance"])}
          />
```
2. The data (result of melt function)
```javascript
[
{ID Year: 1999, variable: "FOB", value: null},
{ID Year: 1999, variable: "CIF", value: 390666793.2382602},
{ID Year: 1999, variable: "Trade Balance", value: -390666793.2382602},
{ID Year: 2000, variable: "FOB", value: null},
{ID Year: 2000, variable: "CIF", value: 699033236.8357185},
{ID Year: 2000, variable: "Trade Balance", value: -699033236.8357185},
{ID Year: 2001, variable: "FOB", value: null},
{ID Year: 2001, variable: "CIF", value: 815740186.0119082},
{ID Year: 2001, variable: "Trade Balance", value: -815740186.0119082}
...
]
```
3. The chart looks like:
<img width="668" alt="captura de pantalla 2017-09-06 a las 2 02 07 p m" src="https://user-images.githubusercontent.com/1203432/30124596-09e8a5b2-930c-11e7-8bcc-ec56bb567f9f.png">

### Your Environment

* Browser Name: chome
* Operating System and Version: mac osx El Capitán

**Comment by davelandry** [comment]
Unable to reproduce: https://jsfiddle.net/4m7dwde4/

@palamago is there any global d3plus configuration in your project that may also be effecting the chart?

**Comment by jspeis** [comment]
I also had a similar issue but it seems like it may be resolved now. Perhaps @palamago you can check if it's working now?

**Comment by palamago** [comment]
No luck here @jspeis 
Let me see if is there any global config anywhere, @davelandry

**Comment by jspeis** [comment]
actually I think I just found the bug try this!

https://jsfiddle.net/qyh46wLu/

**Comment by palamago** [comment]
Yes! @jspeis 
I found the global d3plus config. Looks like something is wrong with the fontSize: () => 12,
I commented those lines and works well:

```javascript
const axisConfig = {
  barConfig: {
    "stroke": "#fff",
    "stroke-width": 1
  },
  gridConfig: {
    "stroke": "#fff",
    "stroke-width": 0
  },
  shapeConfig: {
    fill: "#fff",
    fontColor: "rgba(0, 0, 0, 1)",
    fontFamily: () => "'Yantramanav', sans-serif",
    /*fontSize: () => 12,*/
    stroke: "#fff"
  },
  tickSize: 4,
  titleConfig: {
    fontFamily: () => "'Yantramanav', sans-serif",
    /*fontSize: () => 12,*/
    fontWeight: 600,
    textTransform: "uppercase"
  }
};

export default {
  legendConfig: {
    shapeConfig: {
      fontColor: "rgba(0, 0, 0, 0.8)",
      fontFamily: "'Yantramanav', sans-serif",
      fontResize: false,
      fontSize: 12,
      fontWeight: 400,
      height: () => 20,
      textTransform: "uppercase",
      width: () => 20
    }
  },
  shapeConfig: {
    fontColor: "rgba(0, 0, 0, 0.4)",
    fontFamily: "'Yantramanav', sans-serif",
    fontWeight: 600
  },
  xConfig: axisConfig,
  yConfig: axisConfig
};
```

**Comment by davelandry** [comment]
Aha! Thanks for the great reporting @jspeis and @palamago.

The issue was specifically with the font properties passed to an axis' "titleConfig" property. The code was expecting those properties to be static values (and not accessor functions). I've put in a catch for this, but in the meanwhile, you can fix your code by removing the accessor: https://jsfiddle.net/qyh46wLu/3/
