### ISSUE TITLE
error when applying log scale

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-plot#54]
Trying to apply a log scale to a data set results in an error

### Expected Behavior
Would expect to see a log scale of the data

### Current Behavior
Plot visualization does not render

### Steps to Reproduce (for bugs)
https://jsfiddle.net/9sq7rt50/

**Comment by jspeis** [comment]
@davelandry seems to work for the xConfig but I still seem to have some issues trying to use the log scale on the y axis? 

In the console I see the error ```d3plus-plot.v0.5.full.min.js:7 Uncaught TypeError: this._d3Scale is not a function```

https://jsfiddle.net/atg5unex/

**Comment by davelandry** [comment]
@jspeis sorry about this, just found the bug. it was a problem with inverted log scales (ie. `[100000, -1000]` instead of `[-1000, 100000]`). Will push a release once I resolve d3plus/d3plus-geomap#13
