### ISSUE TITLE
Plot-chart weird render issue

### ISSUE THREAD

**Issue by palamago** [d3plus/d3plus-plot#55]
Weird render issue.

### Expected Behavior

Render the lines in a proper way.

### Current Behavior

Weird hops at the end of each line. ¿data problem?
![sept-15-2017 17-42-01](https://user-images.githubusercontent.com/1203432/30551940-a8744050-9c72-11e7-950e-aab20168e01a.gif)

### Steps to Reproduce (for bugs)

1. Check this live example: https://jsfiddle.net/palamago/m4svsfzp/1/
Consideration 1: Not sure if I'm using the x axis properly, its a date. Maybe here is the problem.
Consideration 2: I'm using d3plus react components.

### Your Environment

* Browser Name: Chrome 
* Operating System and Version: OSX

**Comment by palamago** [comment]
It's working properly on Firefox!
<img width="924" alt="captura de pantalla 2017-09-28 a las 2 15 59 p m" src="https://user-images.githubusercontent.com/1203432/30980501-afed59ba-a457-11e7-90ef-bf28ba0bf68b.png">

**Comment by davelandry** [comment]
@palamago looks to be a problem with how different browsers sort strings (which is how you are passing the month values). The solution is to tell d3plus that the `"Month"` variables are time values: https://jsfiddle.net/m4svsfzp/2/

**Comment by palamago** [comment]
Ahá! Good catch @davelandry thanks!
