### ISSUE TITLE
line charts rendering incorrectly

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-plot#83]
When trying to display a line chart visualization, the lines are not drawn as expected the line segments seem like they are getting drawn out of order.

### Expected Behavior
To see the line rendered correctly as shown in this image:
<img width="943" alt="screen shot 2018-04-03 at 10 54 17 am" src="https://user-images.githubusercontent.com/87581/38259326-b84d605a-3732-11e8-9653-aebb23f27b40.png">

### Current Behavior
Incorrect line chart rendering as shown in this image:

<img width="1027" alt="screen shot 2018-04-03 at 10 53 37 am" src="https://user-images.githubusercontent.com/87581/38259351-c8499186-3732-11e8-9175-40eedbc98405.png">

### Steps to Reproduce (for bugs)

1. https://jsfiddle.net/zk5hnyLc/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: OS X 10.13.3

**Comment by davelandry** [comment]
@nbond211 please take look at this either end of week or next week. It has to be related to one of the releases we've recently done.
